### PR TITLE
Include changes to ECS ALB config in pipeline trigger

### PR DESCRIPTION
**Pull request by blairboy362**

### CODE REVIEW

**Review by szd55gds — APPROVED** [review]
LGTM

**Comment by philandstuff** [comment]
Yeah those ALBs only front alertmanager, so they shouldn't trigger prometheus jobs...

**Comment by philandstuff** [comment]
maybe the paths should be added to `alertmanager-git` instead?

**Comment by philandstuff** [comment]
Argh sorry for triple-post. The problem is that the ALBs are managed in a whole separate project (`terraform/projects/app-ecs-albs-{staging,production}`) and that this project is not CD'd at the moment.  So we need to apply manually or set up a new concourse job.

**Comment by blairboy362** [comment]
> Argh sorry for triple-post. The problem is that the ALBs are managed in a whole separate project (`terraform/projects/app-ecs-albs-{staging,production}`) and that this project is not CD'd at the moment. So we need to apply manually or set up a new concourse job.

Yes, I saw that. I'll tackle this when I've fixed the other stuff that's currently red.

**Pull request merged**
