### PR TITLE
add default.nix

### PR DESCRIPTION
**Pull request by risicle**
Do what you like with this, but this is what I'll probably be using to work with this. Single package manager instead of 3 package managers fighting over the same tools.

### CODE REVIEW

**Review by szd55gds — DISMISSED** [review]
Looks ok to me

**Comment by risicle** [comment]
Sorry, it seems awfully rude "dismissing" your review but really all I did was add some entries to the `.gitignore`.

**Review by philandstuff — COMMENTED** [review]
I tried running `nix-shell .` and got the following:

```
building '/nix/store/r1cjbqlc9zss47j042s8kkh61h7pvaph-terraform-0.12.19.drv'...
unpacking sources
unpacking source archive /nix/store/rn9xdsbjfhfp5g2j31sbbwkjs9cn5gcz-source
source root is source
patching sources
applying patch /nix/store/cps9fyi0wq9jgpila5fzghg6vgkq9zb6-provider-path.patch
patching file command/init.go
Hunk #1 succeeded at 74 with fuzz 2 (offset 10 lines).
applying patch /nix/store/lsavzng3b7nk77qdsc9bwgg0f6q0b0jb-fix-mac-mojave-crashes.patch
patching file helper/wrappedstreams/streams.go
patching file helper/wrappedstreams/streams_other.go
applying patch /nix/store/ixb9mhqsd9i9nl3zjml97xsxqcv336aj-24562.patch
patching file helper/wrappedstreams/streams.go
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file helper/wrappedstreams/streams.go.rej
patching file helper/wrappedstreams/streams_other.go
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file helper/wrappedstreams/streams_other.go.rej
builder for '/nix/store/r1cjbqlc9zss47j042s8kkh61h7pvaph-terraform-0.12.19.drv' failed with exit code 1
cannot build derivation '/nix/store/754s3ack9dlipzgp2c7ki0kya48p9xdc-terraform-0.12.19.drv': 1 dependencies couldn't be built
error: build of '/nix/store/754s3ack9dlipzgp2c7ki0kya48p9xdc-terraform-0.12.19.drv' failed
```

Don't know what's going on here.

**Comment by risicle** [comment]
Are you using nixpkgs `master`? If so you can remove the `patches = ` addition for terraform - I was mostly targeting this at current stable (`release-20.03`)

**Comment by risicle** [comment]
Oh wait it's just because https://github.com/NixOS/nixpkgs/pull/97557 got merged upstream ;)

**Comment by heathd** [comment]
this repo is no longer in use and is being archived. Closing PRs

**Pull request closed without merging**
