### PR TITLE
Remove prometheus alerts for coronavirus services

### PR DESCRIPTION
**Pull request by gclssvglx**
What

The 3 coronavirus services (find support, business volunteer and
vulnerable people) are being shutdown and their infrastructure
removed.

Why

These services are either no longer required, will or have been
re-written or re-created, or have been migrated.

[Trello](https://trello.com/c/fcOEavQD/558-do-this-first-remove-prometheus-alertmanager-monitoring)

### CODE REVIEW

**Review by Krenair — CHANGES_REQUESTED** [review]
You should also remove references from terraform/modules/prom-ec2/paas-config/main.tf and terraform/modules/alertmanager/templates/alertmanager.tpl

**Comment by gclssvglx** [comment]
> You should also remove references from terraform/modules/prom-ec2/paas-config/main.tf and terraform/modules/alertmanager/templates/alertmanager.tpl

Thank you @Krenair 👍

**Review by Krenair — APPROVED** [review]
Sounds good to me but I'd like confirmation from another person involved in these services

**Comment by gclssvglx** [comment]
> Sounds good to me but I'd like confirmation from another person involved in these services

Totally understand - thanks @Krenair

**Review by reggieb — APPROVED** [review]
LGTM

**Pull request merged**
