### PR TITLE
Upgrade Terraform to 0.11.10

### PR DESCRIPTION
**Pull request by issyl0**
# Why I am making this change

We should keep our infrastructure tools up to date. The Terraform changelog is [here](https://github.com/hashicorp/terraform/blob/v0.11.10/CHANGELOG.md).

Testing this might be a good time to try out the `kitchen` tests?

### CODE REVIEW

**Comment by kentsanggds** [comment]
I'll see if I can get them working

**Comment by issyl0** [comment]
I ran a `plan` on my dev stack with this version and things seem to look fine.

**Comment by kentsanggds** [comment]
0.11.9 out now

**Comment by issyl0** [comment]
`0.11.10` is out now.

**Comment by kentsanggds** [comment]
Doh!

**Pull request merged**
