### PR TITLE
Rename DGU organisation

### PR DESCRIPTION
**Pull request by thomasleese**
The organisation name has been renamed in the PaaS.

[Trello Card](https://trello.com/c/032AYbj3/1037-change-the-org-name-in-the-paas)

### CODE REVIEW

**Review by andy-paine — APPROVED** [review]

**Comment by andy-paine** [comment]
I can't actually see any metrics for `gds-data-gov-uk` - is this just in preparation for a move to a new org?

**Comment by thomasleese** [comment]
@andy-paine That's correct, the move hasn't happened yet, I'm just opening various PRs that will need to be merged once it's done.

**Comment by thomasleese** [comment]
@andy-paine Rename is done, I think you should be able to see the metrics now. Are you able to merge this?

**Comment by andy-paine** [comment]
LGTM

**Pull request merged**
